
import java.awt.event.ActionListener;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class Frame extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        btnEvento2.addActionListener(this);
        btnEvento3.addActionListener(this);
        Frame.Manejador m = new Frame.Manejador();
        btnEvento4.addActionListener(m);
        btnEventoCAHU.addActionListener((java.awt.event.ActionEvent evt) -> {
            showMessageDialog(null, "Evento 1.5:Hecho por el usuario.");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEvento1 = new javax.swing.JButton();
        btnEventoCAHU = new javax.swing.JButton();
        btnEvento2 = new javax.swing.JButton();
        btnEvento3 = new javax.swing.JButton();
        btnEvento4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEvento1.setText("Evento1");
        btnEvento1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEvento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvento1ActionPerformed(evt);
            }
        });

        btnEventoCAHU.setText("Evento1.5");

        btnEvento2.setText("Evento2");

        btnEvento3.setText("Evento3");

        btnEvento4.setText("Evento4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEvento1)
                    .addComponent(btnEventoCAHU)
                    .addComponent(btnEvento2)
                    .addComponent(btnEvento3)
                    .addComponent(btnEvento4))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 57, Short.MAX_VALUE)
                .addComponent(btnEvento1)
                .addGap(15, 15, 15)
                .addComponent(btnEventoCAHU)
                .addGap(15, 15, 15)
                .addComponent(btnEvento2)
                .addGap(15, 15, 15)
                .addComponent(btnEvento3)
                .addGap(15, 15, 15)
                .addComponent(btnEvento4)
                .addGap(0, 58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEvento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvento1ActionPerformed
        showMessageDialog(this, "Evento 1: Clase anomima evt.");
    }//GEN-LAST:event_btnEvento1ActionPerformed
public void actionPerformed(java.awt.event.ActionEvent evt) {
    if(evt.getActionCommand().equals("Evento2"))
        showMessageDialog(this, "Evento 2: Clase ventana manejador de eventos.");
    else
        showMessageDialog(this, "Evento 3: Clase ventana manejador de eventos.");
    }

class Manejador implements ActionListener{
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        showMessageDialog(Frame.this, "Evento 4: Clase interna manejador de eventos.");
    }//actionperformed
}//class
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvento1;
    private javax.swing.JButton btnEvento2;
    private javax.swing.JButton btnEvento3;
    private javax.swing.JButton btnEvento4;
    private javax.swing.JButton btnEventoCAHU;
    // End of variables declaration//GEN-END:variables
}
