
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author devilhunter
 */
public class Ventana extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        btnEvento2.addActionListener(this);
        btnEvento3.addActionListener(this);
        Manejador m = new Manejador();
        btnEvento4.addActionListener(m);
        btnEventoCAHU.addActionListener((java.awt.event.ActionEvent evt) -> {
            showMessageDialog(null, "Evento 1.5:Hecho por el usuario.");
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEvento1 = new javax.swing.JButton();
        btnEvento2 = new javax.swing.JButton();
        btnEvento3 = new javax.swing.JButton();
        btnEvento4 = new javax.swing.JButton();
        btnEventoCAHU = new javax.swing.JButton();
        accesoRapido2 = new MenuPrincipal.AccesoRapido();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manejador de Eventos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEvento1.setText("Evento1");
        btnEvento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvento1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEvento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnEvento2.setText("Evento2");
        getContentPane().add(btnEvento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        btnEvento3.setText("Evento3");
        getContentPane().add(btnEvento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        btnEvento4.setText("Evento4");
        getContentPane().add(btnEvento4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        btnEventoCAHU.setText("Evento1.5");
        getContentPane().add(btnEventoCAHU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        accesoRapido2.setIcono(new javax.swing.ImageIcon(getClass().getResource("/1.png"))); // NOI18N
        accesoRapido2.setTexto("Tienda");
        getContentPane().add(accesoRapido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEvento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvento1ActionPerformed
        showMessageDialog(this, "Evento 1: Clase anomima evt.");
    }//GEN-LAST:event_btnEvento1ActionPerformed
public void actionPerformed(java.awt.event.ActionEvent evt) {
    if(evt.getActionCommand().equals("Evento2"))
        showMessageDialog(this, "Evento 2: Clase ventana manejador de eventos.");
    else
        showMessageDialog(this, "Evento 3: Clase ventana manejador de eventos.");
    }

class Manejador implements ActionListener{
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        showMessageDialog(Ventana.this, "Evento 4: Clase interna manejador de eventos.");
    }//actionperformed
}//class
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MenuPrincipal.AccesoRapido accesoRapido2;
    private javax.swing.JButton btnEvento1;
    private javax.swing.JButton btnEvento2;
    private javax.swing.JButton btnEvento3;
    private javax.swing.JButton btnEvento4;
    private javax.swing.JButton btnEventoCAHU;
    // End of variables declaration//GEN-END:variables
}
